### ISSUE TITLE
deepsurv import error

### ISSUE THREAD

**Issue by azenin** [jaredleekatzman/DeepSurv#5]
Hi,

```
>>> import deepsurv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/deepsurv/__init__.py", line 1, in <module>
    from .deep_surv import DeepSurv
  File "/usr/local/lib/python2.7/dist-packages/deepsurv/deep_surv.py", line 1, in <module>
    import lasagne
  File "/usr/local/lib/python2.7/dist-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
>>> import theano
>>> theano.__version__
'0.9.0'
```
Ubuntu 16.04 LTS

**Comment by dareneiri** [comment]
This issue isn't related to deepsurv but is a frequent problem observed with people using theano and lasagne. My recommendation is reinstall theano and lasagne (since they both rely on each other) with the bleeding-edge version: http://lasagne.readthedocs.io/en/latest/user/installation.html

```
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
```
